# 01: SQL Basics (CS50 SQL)
This notebook walks through the basic commands of SQL: `SELECT`, `WHERE`, `LIKE`, `ORDER BY`, and `LIMIT` using Python's `sqlite3` and `pandas` libraries on the `favorites` database.

### Setup: Connect to Database
We establish a connection to our database and check the table structure.

In [8]:
import os
import sqlite3
import pandas as pd

# Locate the database
db_path = os.path.join("..", "databases", "favorites.db")
conn = sqlite3.connect(db_path)

# Verify the schema of favorites table
pd.read_sql_query("PRAGMA table_info(favorites);", conn)

   cid       name     type  notnull dflt_value  pk
0    0         id  INTEGER        0       None   1
1    1  Timestamp     TEXT        0       None   0
2    2   language     TEXT        0       None   0
3    3    problem     TEXT        0       None   0

### 1. The `SELECT` Clause
**What SQL concept is demonstrated?**
We query specific columns or all columns from the `favorites` table using `SELECT`.

In [9]:
# Querying all columns but limiting rows to 5
query = """
SELECT * 
FROM favorites 
LIMIT 5;
"""
pd.read_sql_query(query, conn)

   id            Timestamp language                problem
0   1   10/20/2025 9:45:26   Python            Readability
1   2  10/20/2025 10:08:03   Python                  Mario
2   3  10/20/2025 11:20:23   Python                 Filter
3   4  10/20/2025 13:37:05   Python  Starting from Scratch
4   5  10/20/2025 13:37:06  Scratch  Starting from Scratch

In [10]:
# Selecting specific columns
query = """
SELECT language, problem 
FROM favorites 
LIMIT 5;
"""
pd.read_sql_query(query, conn)

  language                problem
0   Python            Readability
1   Python                  Mario
2   Python                 Filter
3   Python  Starting from Scratch
4  Scratch  Starting from Scratch

### 2. The `WHERE` Clause
**What SQL concept is demonstrated?**
We filter rows where a specific condition is met.

In [11]:
# Selecting only records where the language is Python
query = """
SELECT id, Timestamp, language, problem 
FROM favorites 
WHERE language = 'Python'
LIMIT 5;
"""
pd.read_sql_query(query, conn)

   id            Timestamp language                problem
0   1   10/20/2025 9:45:26   Python            Readability
1   2  10/20/2025 10:08:03   Python                  Mario
2   3  10/20/2025 11:20:23   Python                 Filter
3   4  10/20/2025 13:37:05   Python  Starting from Scratch
4   6  10/20/2025 13:37:07   Python                 Credit

### 3. The `LIKE` Wildcard Matching
**What SQL concept is demonstrated?**
Using `LIKE` with wildcards (`%`) to search for string patterns inside text columns.

In [12]:
# Find records where problem contains 'Scratch' anywhere in the name
query = """
SELECT * 
FROM favorites 
WHERE problem LIKE '%Scratch%'
LIMIT 5;
"""
pd.read_sql_query(query, conn)

   id            Timestamp language                problem
0   4  10/20/2025 13:37:05   Python  Starting from Scratch
1   5  10/20/2025 13:37:06  Scratch  Starting from Scratch
2  13  10/20/2025 13:37:15   Python  Starting from Scratch
3  24  10/20/2025 13:37:19  Scratch  Starting from Scratch
4  25  10/20/2025 13:37:19   Python  Starting from Scratch

### 4. Sorting with `ORDER BY`
**What SQL concept is demonstrated?**
Sorting result sets alphabetically or numerically in ascending (`ASC`) or descending (`DESC`) order.

In [13]:
# Sort distinct problems alphabetically
query = """
SELECT DISTINCT problem 
FROM favorites 
ORDER BY problem ASC;
"""
pd.read_sql_query(query, conn)

                  problem
0                  Caesar
1                    Cash
2                  Credit
3                     DNA
4                  Filter
5          Hello, It's Me
6            Hello, World
7             Inheritance
8                   Mario
9               Plurality
10            Readability
11                Recover
12                 Runoff
13               Scrabble
14                   Sort
15                Speller
16  Starting from Scratch
17           Substitution
18                Tideman
19                 Volume

### Clean Up
We close the database connection.

In [14]:
conn.close()
print("Connection closed.")

Connection closed.

### Reflection
**What did I learn?**
- `SELECT` retrieves specific columns of data.
- `WHERE` enables row-level filtering.
- `LIKE` allows fuzzy text matching using `%` as wildcards.
- `ORDER BY` lets us sort output tables cleanly.
- `LIMIT` controls the size of output tables, which is useful when dealing with large datasets.